# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e5224cea16ef51073da56daf386c4f54564f55fb33026bad8f146c2e50bf035752afd47aeae2c58b6c2b7b29de3dc7e58db058064db3f72887a80554cd21b01

test:
  secret_key_base: d1fc20e3560cf09c6a0d46fae09c6c1ace49e9b5c202ee18cb413a0cb7da3a601586709a51e104d24432e59c449bc179d14a907df964ad13b53a9afd215c29e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
